### ISSUE TITLE
Support Istio Integration

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#12]
Istio [Ingress Gateway](https://istio.io/latest/docs/tasks/traffic-management/ingress/ingress-control/) is an Envoy-based edge proxy that is managed by Istiod and integrates with the Istio service mesh. Should EG be considered as a replacement? If so, why? What are the benefits of using EG for mesh ingress instead of Istio Ingress Gateway? Do other opportunities exist to integrate with Istio?

**Comment by rahulanand16nov** [comment]
I have a similar question since Istio provides its own implementation of Gateway API that translates into Envoy Proxy config and EG is trying to achieve a similar thing. How does EG differ from Istio's implementation of Gateway API?

**Comment by arkodg** [comment]
Here are some of the similarities between the Envoy Gateway project and the Istio project
* They both plan on supporting the Gateway API (Istio already supports most of it today)
* Both use Envoy Proxy in the data plane

Here are some of the differences 
* Istio manages the ingress gateways as well as sidecar proxies managing north-south as well east-west traffic
* Envoy Gateway's scope is limited to managing north-south traffic
* Envoy Gateway aims to run on all environments (k8s and non k8s)

What does this mean for the end user
* They would have the flexibility to easily migrate from the Envoy Gateway control plane to the Istio control plane and vice versa since the configuration intent would be the same (using Gateway API)
* They could start off using Envoy Gateway to solve their north-south API Gateway use cases and then migrate to the Istio project to also leverage the service mesh architecture (authoring east-west policies)
* It is unlikely that the user would run both the control planes (Envoy Gateway and Istio) together, unless both the projects end up differing on custom Gateway API definitions.

What does this mean from an implementation perspective
* It would definitely make sense to leverage a lot from the Istio project since it is a mature project, and is heavily used in production today. These learnings could either be proactively incorporated as design decisions while designing system components or we could share common code between projects as libraries.
* Some system components might differ due to the difference in project goals e.g. Envoy Gateway plans on using the go-control-plane project as the xDS Server, and Istio does not - since it deals with a higher scale of data plane Envoy proxies and cannot accommodate all xDS resources in a in-memory snapshot (which go-control-plane uses).

Hope this helps understand how the two projects are related, IMHO the end user is the winner who will have more options soon for deciding on Envoy based APIGateways, as well as a reference implementation native to the Envoy project.
