### ISSUE TITLE
Support IP whitelist

### ISSUE THREAD

**Issue by uniduan** [envoyproxy/gateway#1447]
*Description*:
Does envoy gateway support IP whitelist? 
How to use it?

**Comment by oowl** [comment]
I see that the code base only supports JWT authentication for now, but luckily Envoy has an RBAC filter that can meet your needs. https://www.envoyproxy.io/docs/envoy/v1.9.0/api-v2/config/rbac/v2alpha/rbac.proto#envoy-api-field-config-rbac-v2alpha-principal-source-ip

**Comment by oowl** [comment]
If possible, I can try to support this. What do you think? @arkodg

**Comment by uniduan** [comment]
Thanks for your help. I'll try the RBAC filter.

**Comment by arkodg** [comment]
reopening this issue, and adding the help-wanted label in case someone from the community wants to take this forward

We now have an API to be able to hold this feature - [ClientTrafficPolicy](https://gateway.envoyproxy.io/latest/api/extension_types.html#clienttrafficpolicy) which is a good home for this feature

Temporary solution: we've added support for EnvoyPatchPolicy https://gateway.envoyproxy.io/latest/user/envoy-patch-policy.html which can be used to directly configure the RBAC Filter
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/rbac/v3/rbac.proto#envoy-v3-api-msg-config-rbac-v3-rbac

**Comment by Xunzhuo** [comment]
Should be better to add into SecurityPolicy ? @envoyproxy/gateway-maintainers

**Comment by arkodg** [comment]
a decision needs to be made here on whether ip blocking is part of `SecurityPolicy` or `ClientTrafficPolicy` . This boils down to use cases -
* if ip blocking is handled primarily by network admin / platform admin, it should be included in `ClientTrafficPolicy`
* if ip blocking is defined by app devs, it should be made part of `SecurityPolicy`

I vote to make it part of `ClientTrafficPolicy` because Ive seen network/infra admins perform this op. App Devs can always use rate limiting to limit requests from a specific subset of IPs to a small value or `0` for their business use case

**Comment by zzjin** [comment]
May [GEP-713](https://gateway-api.sigs.k8s.io/geps/gep-713/) can solve this problem?

eg:

* app devs can define ip whitelist/blacklist policy and attach it to *route
* sysadm can also define these policy and attach to gateway(and/or sub route), and even drop app devs policy.
*

**Comment by arkodg** [comment]
@zzjin `SecurityPolicy` & `ClientTrafficPolicy` are implementations of https://gateway-api.sigs.k8s.io/geps/gep-713/

**Comment by arkodg** [comment]
dup of https://github.com/envoyproxy/gateway/issues/2462
