### ISSUE TITLE
translator: add name

### ISSUE THREAD

**Issue by zirain** [envoyproxy/gateway#1640]
1. add Name on https://github.com/envoyproxy/gateway/blob/773bdfbefc769f51779d5056547e88d12e1d9508/internal/xds/translator/translator.go#L27
2. use `namespace/name` as fortmat

cc @arkodg

**Comment by arkodg** [comment]
+1, we should use `/` everywhere including in the helpers here https://github.com/envoyproxy/gateway/blob/ab7aed6ad997216853325a64bdb708064e6de594/internal/gatewayapi/helpers.go#L388
this is a breaking change and should be added to the release notes for v0.5.0

**Comment by arkodg** [comment]
there is a issue with replacing `-` to `/` everywhere, this will not work in the infra layer that uses the IR name (`<namespace>-<name>` to `<namespace>/<name>`) to create k8s deployment names
https://github.com/envoyproxy/gateway/blob/609949d6dfcc3726a78a7d6cbb7b6298883159fa/internal/infrastructure/kubernetes/proxy/resource_provider.go#L180

**Comment by zirain** [comment]
1. strings.Replace("", "/", "-", -1)
2. I'm not a big fan of put all gateway in a single namespace.

**Comment by zirain** [comment]
BTW, is this a block for https://github.com/envoyproxy/gateway/pull/1629?

**Comment by arkodg** [comment]
> BTW, is this a block for #1629?

non blocking, but related imo, approved the PR

**Comment by arkodg** [comment]
Highlighting the name collision issue and potential solution in more detail
Issue
* EG accepts `Gateway` resources from multiple namespaces and generates/deploys K8s resources such as Deployment mapping to each of these Gateways in the system namespace where EG is running
* EG currently creates internal IR names using this logic =  `<GatewayNamespace>-<GatewayName>`
The issue here can be highlighted with this example
  * Gateway1: NS1 = foo Name1 = bar-baz IRName1 = foo-bar-baz
  * Gateway2: NS2 = foo-bar Name2 = baz IRName2 = foo-bar-baz

* Above example shows that two different Gateways in different namespaces can end up creating the same IR Name which will cause a resource creation collision since they will created in the same namespace (system namespace / `envoy-gateway-system`)

Potential Solution
* Use a separator that cannot be part of the `Gateway` name such as `/` when generating IR Names
* When generating K8s resource names from IR Names, replace `/` with `-` as the separator, but also append the unique hash based on the IR Name ensuring uniqueness
* PoC in https://github.com/envoyproxy/gateway/pull/1681


ptal @envoyproxy/gateway-maintainers
