### ISSUE TITLE
Getting "No addresses have been assigned to the Gateway" when deploying gateway in k3d

### ISSUE THREAD

**Issue by mwoodpatrick** [envoyproxy/gateway#1654]
*Description*:
Getting "No addresses have been assigned to the Gateway" when deploying gateway in k3d

[optional *Relevant Links*:]
I'm following the example [HTTP Routing — Envoy Gateway documentation (envoyproxy.io)](https://gateway.envoyproxy.io/v0.4.0/user/http-routing.html) using a k3d cluster running on WSL-2. It appears that the gateway class was deployed correctly but after installing the Install the HTTP routing example resources the gateway status is still showing "No addresses have been assigned to the Gateway"

For details please see log [here](https://github.com/mwoodpatrick/k3d-metallb-starter-kit/blob/master/scripts/deploy_envoy_gateway/http_routing/deploy.log)

Please let me know if you have any suggestions as to what the issue is or best way to debug

**Comment by arkodg** [comment]
@mwoodpatrick this is most likely happening because `k3d` might not have assigned a `LoadBalancer` IP to the generated EnvoyProxy service which you can confirm by reviewing the service output
```
kubectl get svc -n envoy-gateway-system --selector=gateway.envoyproxy.io/owning-gateway-namespace=default,gateway.envoyproxy.io/owning-gateway-name=eg -o yaml
```
this shouldnt have any negative impact regarding programming the data plane.
you should still be able to test your intent locally by port forwarding, highlighted here
https://gateway.envoyproxy.io/v0.4.0/user/quickstart.html#testing-the-configuration

**Comment by dereknex** [comment]
Same issue, looks like service is not created automatically.

**Comment by dereknex** [comment]
change the solver from http01 to dns01, and that fixed the problem.

**Comment by arkodg** [comment]
closing as doesnt seem like an issue related to EG
