### ISSUE TITLE
Traffic flows with `Host: <host>:<port>` not allowed when hostname is set in HTTPRoute not Listener

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#1687]
*Description*:

Related https://github.com/envoyproxy/gateway/pull/1478#issuecomment-1644126796

**Comment by arkodg** [comment]
as @jackkleeman already pointed out, EG maps the listener hostname into the IR listener hostname which maps to the Domains field in Virtual Hosts, but maps the http route hostname into IR Header matches
https://github.com/envoyproxy/gateway/issues/680 can fix this issue

**Comment by jackkleeman** [comment]
I am currently working on a POC PR where we just use a virtualhost per domain we want to match against within a listener, instead of this :authority header match approach. Would you be happy with that?

**Comment by jackkleeman** [comment]
for the time being as a workaround ive modified my crd to allow the use of : in header match name; that way i can just use an explicit match on :authority. i dont think theres any other way to do it right now

**Comment by arkodg** [comment]
> I am currently working on a POC PR where we just use a virtualhost per domain we want to match against within a listener, instead of this :authority header match approach. Would you be happy with that?

how do you plan on mapping it from an IR perspective ?

imo it might be easier to map the output of [computeHosts](https://github.com/envoyproxy/gateway/blob/3f503723f2a6eedaa20ce8c5200f57087c7be52d/internal/gatewayapi/helpers.go#L165) to [this](https://github.com/envoyproxy/gateway/blob/0366b5cf66206dd5a4884089056c9bbf69d3702c/internal/ir/xds.go#L138)

**Comment by tmsnan** [comment]
[IgnorePortInHostMatching won't work for :authority exact/suffix header matching](https://github.com/envoyproxy/gateway/pull/1478#issuecomment-1644126796) . because `IgnorePortInHostMatching` takes effect in find VirtualHost which matches the domain. https://github.com/envoyproxy/envoy/blob/ac42ba030f81a787d7bae7c3d0f59070ca7633ba/source/common/router/config_impl.cc#L1986C2-L1999C47

**Comment by jackkleeman** [comment]
I've created a branch here with a proposal approach: https://github.com/envoyproxy/gateway/compare/main...jackkleeman:gateway:virtualhost2?expand=1

The general idea is that instead of creating a route in the IR per intersecting domain in the HTTPRoute, where each route has an :authority check, we just store in the IR the computed intersecting domains. Then, when creating the XDS, we use those domains to create more than one virtualhost - one per domain that we care about. then, we map each route into each virtual host that it matches into; so routes with domain *.example.com must go in the virtual host for foo.example.com AND *.example.com

the XDS logic here is a bit unpleasant. if we like this general approach, I can pull it out into individual tested functions so we have some confidence. i have added a new test that covers the whole PR; the current test coverage for the case with lots of different intersecting domains was quite poor

**Comment by arkodg** [comment]
thanks for working on this @jackkleeman, took a peek into your branch and saw a lot of changes in the xds translator layer.
imo this can be solved in the gateway api layer w/o any changes in other places
Here is a suggestion
* copy the o/p of [hosts](https://github.com/envoyproxy/gateway/blob/60e5f719f7a295b0b1f4e0bee20aa2ad6182d6ac/internal/gatewayapi/route.go#L483) into `irListener.Hostnames` . 
* above hosts might need to get scrubbed to ensure there are no duplicates, if envoy doesnt like it
* you can now also delete all the logic around header match of `:authority`
https://github.com/envoyproxy/gateway/blob/60e5f719f7a295b0b1f4e0bee20aa2ad6182d6ac/internal/gatewayapi/route.go#L493

**Comment by jackkleeman** [comment]
how does that work? dont we need to be able to address specific routes by hostname? eg:
listener: *.example.com
route1: foo.example.com
route2: bar.example.com

with your suggestion, the listener would be for *.example.com foo.example.com bar.example.com and the routes would have no hostname selectivity. so wouldnt all traffic go to both routes?

**Comment by arkodg** [comment]
![giphy (1)](https://github.com/envoyproxy/gateway/assets/9469142/37dd95a5-61d0-4298-ad58-a10e2ac170b5)

**Comment by arkodg** [comment]
youre absolutely right @jackkleeman , thanks for the correction, can you raise your changes as a PR, will raise this issue
in the community meeting since this design moves HTTPRoutes to Xds VirtualHost from N to 1 to 1:1

**Comment by arkodg** [comment]
hey @jackkleeman, @zirain @AliceProxy and I discussed this issue in the community meeting today, and we were a -1 on using the regex approach which would slow down every data plane request, so indirectly +1 to your suggested idea of creating a new xds virtual host per IR route, will make sure to review your PR this week, thanks for raising it

**Comment by jackkleeman** [comment]
ok, thanks!
