### ISSUE TITLE
Internal Metadata API

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#173]
*Description*:
Design an internal metadata API used by all IR objects. Potential use cases:
1. Used to reference the external object(s) that were used to create the IR object.
2. Others?

[optional *Relevant Links*:]
https://github.com/envoyproxy/gateway/issues/119
https://github.com/envoyproxy/gateway/issues/32

**Comment by youngnick** [comment]
In our community meeting, @danehans mentioned the idea of using annotations on the source resources rather than storing this information in the IR itself.

I think that _may_ be a good idea for this, but we'll need to be really careful about how much API server load this generates when there are a lot of Gateway API resources under management.

Another approach is one @LukeShu mentioned when we discussed this earlier - instead, we can store the Kubernetes self-reference URL for Kubernetes resources, and some other URL for non-Kubernetes config sources. And then the providers can have some interface that knows how, for a particular config URL, to tell the owner of that config that there's a problem with it.

**Comment by danehans** [comment]
MOved this into 0.2.0-rc2 since it's required for https://github.com/envoyproxy/gateway/issues/330

**Comment by danehans** [comment]
> Another approach is one @LukeShu mentioned when we discussed this earlier - instead, we can store the Kubernetes self-reference URL for Kubernetes resources, and some other URL for non-Kubernetes config sources. And then the providers can have some interface that knows how, for a particular config URL, to tell the owner of that config that there's a problem with it.

@LukeShu @youngnick `selfLink` is deprecated and is no longer populated by Kubernetes.

**Comment by danehans** [comment]
Since `selfLink` is deprecated, I plan to proceed with:

1. Adding `metadata.labels` to the Infra IR.
2. Creating label keys for each Gateway's ns/name.
3. Having the translator apply these labels to infra IR `metadata.labels`.
4. Update the Kube Infra Manager to apply these infra IR labels to managed resources.

xref: https://github.com/envoyproxy/gateway/pull/328
