### ISSUE TITLE
Add Service Watch to HTTPRoute Controller

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#189]
*Description*:
Add a Service controller to the Kubernetes Provider package similar to the [HTTP Route Controller](https://github.com/envoyproxy/gateway/pull/179) that will be needed by the [Gateway API Translator](https://github.com/envoyproxy/gateway/blob/c83b7b04530f1cbdeb4e9596d0781eb8a2e1317b/internal/gatewayapi/translator.go#L23)

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by danehans** [comment]
The Kube provider should not need a service controller. Since Services are a dep of HTTPRoutes, the httproute controller should include a watch for services. When a service is CRUD'ed, an HTTPRoute reconciliation will be triggered by the httproute controller. The controller should get/list the necessary objects, e.g. Gateways, Services, etc required to call the translate func or pub the translate message. Post v0.2.0, we should consider an approach to filter the services to reduce the reconciliation churn.

**Comment by arkodg** [comment]
reopened this issue since we haven't yet reconciled and stored the service resources in the provider resources message

**Comment by skriss** [comment]
xref https://github.com/envoyproxy/gateway/pull/230#discussion_r953151075, need to decide on the pattern for this
