### ISSUE TITLE
mapping scheme from Service ports to ports that Envoy listens on

### ISSUE THREAD

**Issue by skriss** [envoyproxy/gateway#192]
We'll need to sort out how ports on the service map to ports that Envoy listens on. Right now they're 1:1, but I imagine inside the Envoy container we'll want to listen on e.g. 8080/8443, and then have the Service map 80->8080 and 443->8443. However, since we need to handle arbitrary ports, not just those two, we'll need some kind of mapping scheme. I'll file an issue for this.

_Originally posted by @skriss in https://github.com/envoyproxy/gateway/pull/188#discussion_r937085989_

**Comment by danehans** [comment]
Currently, `gateway.spec.listeners[].port` is processed differently between xds and infra IRs. The infra IR uses this port for the Kube Envoy service port. The xds IR uses this port for envoy listeners.

## Option 1
Have the xds IR use the container ports of the envoy pod for listener ports when provider=Kube. To accomplish this, the continerPorts can be configurable (defaulting to http=8080/https=8443) through the EnvoyProxy API. The EnvoyProxy is referenced by the managed GatewayClass. If unreferenced the xds IR should use the default ports for Envoy listeners. Otherwise, get the ports from referenced EnvoyProxy.

## Option 2:
Keep the xds IR as-is. Instead, have the infra IR use `gateway.spec.listeners[].port` to configure Envoy's containerPorts instead of Envoy service ports. Instead, have the service ports configurable (defaulting to http=80/https=443) through the EnvoyProxy API. The EnvoyProxy is referenced by the managed GatewayClass. If unreferenced the infra IR should use the default ports for the Envoy container ports. Otherwise, get the container ports from referenced EnvoyProxy.

**Comment by arkodg** [comment]
* the good news here is that EG can the flexibility to control Service->Container port mappings.
* for every service port / gateway listener port , the gateway api translator could generate a container port (which might need to be in the unprivileged port range 1024-65535)
* the gatewayapi translator needs to pass the service port and the container port to the Infra manager via the infra IR
* the gatewayapi translator needs to pass the container port in the Xds IR
