### ISSUE TITLE
Scale: Enabling leader election or Multiple EG writing status back for same resource.

### ISSUE THREAD

**Issue by Xunzhuo** [envoyproxy/gateway#1953]
*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

Envoy Gateway disabled leader election at default and didn`t expose it through envoy gateway config. When scaling cp replicas, Multiple EG will be writing status back for same resource.

We need to find out which is more expensive - enabling leader election and EG sending heartbeats to API server or multiple EG writing status back for same resource.

cc @envoyproxy/gateway-maintainers 

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by zirain** [comment]
> Envoy Gateway disabled leader election at default and didn`t expose it through envoy gateway config.

this suprise me, IMO, EG should enable leader election.

**Comment by arkodg** [comment]
imo we should enable leader election (by default) to make sure only 1 EG controller can
  *  **write status** back
  *  can **create/write infra** (envoy proxy fleet & rate limit service)
  
but we need to make sure all EGs can **read/watch resources** and generate resources so any Envoy proxy can connect to it to get xds to support data plane scale out

cc @Xunzhuo can you help with this since you raise https://github.com/envoyproxy/gateway/pull/2123 :)

**Comment by alexwo** [comment]
Hi, I'm interested in contributing. Could you please assign me to this issue?

**Comment by arkodg** [comment]
thanks for picking this one up and detailing your plans !

approach LGTM, my suggestion would be to not spend any extra efforts on `Readiness Probes Adjustment` and disable the other replicas , and instead invest it directly on `Multi-Replica xDS Service` ( which is how its designed today where `kube-proxy` is helping us spread the load today to different xDS servers ). 
Only after 1 & 2, can we recommend users to confidently scale EG replicas

**Comment by alexwo** [comment]
That sounds like a plan. We can move forward with implementing a comprehensive solution for xDS right from the start. 
Do you think it could still be beneficial to have an option for a deployment where only a single xDS instance is active? 
This setup might ensure better consistency, especially in scenarios where, for example, one replica might become outdated due to a synchronization issue, leading to potential discrepancies to some of it's connected envoys?

**Comment by arkodg** [comment]
> @arkodg That sounds like a plan. We can move forward with implementing a comprehensive solution for xDS right from the start.
> 
> Is it still be beneficial to have an option for a deployment where only a single xDS instance is active & supported by a standby replica ? This could offer better consistency and reliability, especially in scenarios where synchronization issues might lead to a replica becoming outdated.

we could consider Active/Passive control plane replica as Phase 3 :) , as an opt in, would be good to create a sub issue and get community feedback

**Comment by alexwo** [comment]
Yes, sounds like phase3  :) 👍

**Comment by alexwo** [comment]
Use Cases Validated:

1. Blocking the GRPC Port of a Leader (with IP Tables Rule)
Result: the Envoy proxy is able to discover the xDS rules from at least one of the remaining EGs. 

2. Blocking the GRPC Port of the leader + all secondary pods except one
Result: Despite the widespread blockage, the Envoy proxy manages to obtain xDS rules from the remaining unblocked EG, maintaining operational resilience.

3. Apply k8s quickstart ( confirm only leader update status / infra)
Result: status updates and infrastructure are exclusively managed by the leader controller.  

4. K8S control plane API is not available for the leader instance
The leader restarts, however, other instances continue to serve xDS and take leadership when possible

**Comment by arkodg** [comment]
completed with #2694
