### ISSUE TITLE
Allow users to configure xDS resources

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#24]
Users might want to directly configure [xDS Resources](https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol#resource-types) in case Envoy Gateway's API doesn't support their use case.
They might want to add/merge/remove/replace xDS resources that are pushed by Envoy Gateway into Envoy Proxy.
Projects such as Istio provide APIs such as [EnvoyFilter](https://istio.io/latest/docs/reference/config/networking/envoy-filter/) to fulfill these use cases.

Outlining work items

- [x]  Define and Design API https://github.com/envoyproxy/gateway/pull/1410
- [x] Implement API in the Xds Translator https://github.com/envoyproxy/gateway/pull/1606
- [x] Implement support in `egctl` for offline verification https://github.com/envoyproxy/gateway/pull/1682
- [x] Add status to Policy to show runtime status https://github.com/envoyproxy/gateway/pull/1691
- [x] E2E https://github.com/envoyproxy/gateway/pull/1738
- [x] Docs https://github.com/envoyproxy/gateway/pull/1733

**Comment by NomadXD** [comment]
@youngnick What Policy APIs you are referring here ? Kubernetes Gateway API policy attachment ? https://gateway-api.sigs.k8s.io/references/policy-attachment/

**Comment by youngnick** [comment]
Sorry @NomadXD, I missed this.

There are both extension points (usually using an `extensionRef` field that is a reference to an arbitrary CRD, to be defined by the implementation), and Policy Attachment, which is intended for settings that can affect multiple resources (like setting a default for HTTPRoute timeout at the Gateway level by attaching a TimeoutPolicy to the Gateway).

**Comment by zhaohuabing** [comment]
Although it could potentially cause unintended changes in the generated xds and break the whole system, EnvoyFilter is really a powerful API. I think the best use case for EnvoyFilter is it allows other extenstions servers to generate patch for xds. In Aeraki Mesh project, we use EnvoyFilter API to support non-HTTP protocols in Istio. IMHO, EnvoyFilter could also be benificial for use cases like that in Envoy Gateway.

EnvoyFilter is a powerful API, but it should be used with caution since it could cause unintended changes in the generated xds, potentially leading to system failure. However, it is an excellent tool for generating patches for xds in a non-intrusive way. For example, in the Aeraki Mesh project, we use the EnvoyFilter API to support non-HTTP protocols in Istio. In my opinion, a similar mechanism could also be beneficial for such use cases in Envoy Gateway.

**Comment by zirain** [comment]
My concern is `EnvoyFilter` design for fine-tuning in istio, if `EG` provide an elegant way to extend XDS, that would be great.

**Comment by zhaohuabing** [comment]
If Istio had a webhook mechanism in place, EnvoyFilter might not have been necessary.
