### ISSUE TITLE
Consolidate Namespaces

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#254]
Currently, the script behind the `kube-deploy` Make target creates two namespaces, "gateway-system" and "envoy-gateway-system". Instead of requiring two Namespaces to run EG, I suggest we consolidate on the "gateway-system" Namespace name.

Note that the "gateway-system" Namespace is created by the Gateway API [install script](https://github.com/kubernetes-sigs/gateway-api/releases/download/v0.5.0/experimental-install.yaml).

@youngnick is there any reason why the Gateway API admission controller should be in a different Namespace than EG?

**Comment by robscott** [comment]
At least from my perspective, the intent with "gateway-system" was to reserve it for anything released by Gateway API (limited to the webhook right now). That is not currently documented and likely should be. I would personally suggest deploying Envoy Gateway in a separate namespace.

**Comment by youngnick** [comment]
Yes, I agree that we should leave `gateway-system` to the Gateway API, and probably suggest `eg-system`, `envoy-gateway`, or `envoy-gateway-system` for EG.

The reason here is that in my experience, it's better to keep the namespace boundary equivalent to the application boundary. Having two applications that are closely related, but have separate lifecycles sharing a namespace sounds like a problem waiting to happen to me. Namespaces are almost-zero cost, so I think it's better to maximize our cleanliness in this area.

**Comment by danehans** [comment]
@robscott @youngnick thanks for the feedback. I suggest we keep the "envoy-gateway-system" namespace for v0.2.0. I'm moving this issue to the backlog so we can discuss during planning after the release.

**Comment by arkodg** [comment]
@danehans can we close this issue ?

**Comment by danehans** [comment]
Yes, the 2 namespaces are required to split WG and Gateway API.
