### ISSUE TITLE
Pin default Envoy and RateLimit images tags

### ISSUE THREAD

**Issue by shahar-h** [envoyproxy/gateway#2619]
*Description*:
Currently `envoyproxy/envoy-dev:latest` and `envoyproxy/ratelimit:master` are used as default  envoy and ratelimit images.
https://github.com/envoyproxy/gateway/blob/c6696d9c82f1b8c77ccc8e22965d158691cbbd07/api/v1alpha1/shared_types.go#L22

Wouldn't it be better to pin both images to an immutable latest stable tag?
for envoy: `envoyproxy/envoy:distroless-v1.29.1-latest`
for ratelimit: `envoyproxy/ratelimit:9901a9bf`

This way EG installation will be consistent.

In addition, in latest EG release(v0.6.0) `envoyproxy/envoy:distroless-v1.28-latest` is used as default envoy image. A latest stable immutable tag should also be used here.

WDYT?

**Comment by arkodg** [comment]
* For the `main` branch we try and use the `latest`  bits for upstream dependencies (`envoy-proxy`, `envoy-ratelimit`)
Although this may cause some instability due to bugs in the dependencies, the longer soak time before a release outweighs the cons.
* For release images we always pin it for stability. 
  * The caveat here is we didnt pin the envoy image to exact patch version for v0.X releases and only pinned it to a minor version (e.g. `v1.29.1-latest`) to conserve our efforts, yet provide a way to the user to get the latest CVE free envoy image tied to a minor version (by performing a restart). This will change post v1.X releases where we will have to pin to a envoy patch version and will have to release a new EG patch version every time theres a new patch release in Envoy around fixing CVEs
  
  Hope this helps
