### ISSUE TITLE
bug: translation mistake in retry triggers

### ISSUE THREAD

**Issue by guydc** [envoyproxy/gateway#2755]
*Description*:
The EG interface uses the term `disconnect-reset`, while the underlying xds enum value is `reset`. 
Envoy fails silently and accepts misconfiguration. 

I think that the EG term is better, as `reset` is an overloaded term, and the `disconnect-` prefix helps users understand the difference between the `connection-failure` and the `disconnect-reset` triggers. 

The cluster translator should be fixed and translate `disconnect-reset` to `reset`.

**Comment by arkodg** [comment]
thanks for finding this one :) 
I'd vote for `reset` at the API level since it keeps all EG to Envoy docs 1:1 for this feature
https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter#x-envoy-retry-on
and imho `disconnect` and `reset` kinda mean the same thing
@envoyproxy/gateway-maintainers can you chime in as well

**Comment by guydc** [comment]
> thanks for finding this one :) I'd vote for `reset` at the API level since it keeps all EG to Envoy docs 1:1 for this feature https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter#x-envoy-retry-on and imho `disconnect` and `reset` kinda mean the same thing @envoyproxy/gateway-maintainers can you chime in as well

Yea, I see your point about consistency here. I changed the interface as well in a new commit. Let's try to get it in before v1.0.0 to avoid breaking the API later.
