### ISSUE TITLE
Support Endpoint Stats

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#2824]
*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

Add support for enabling per endpoint stats in envoy 
https://github.com/envoyproxy/envoy/pull/29709

https://gateway.envoyproxy.io/latest/api/extension_types/#proxymetrics

Will help with traffic splitting telemetry https://github.com/envoyproxy/gateway/issues/2809

**Comment by ShyunnY** [comment]
I want to try doing this, but I'm not sure if I have the right idea. Do we just need a bool as a switch to enable per endpoint stats on envoy? can you tell me more :)

**Comment by arkodg** [comment]
yup `bool` pointer is the way to go here :)

**Comment by ShyunnY** [comment]
When implementing this feature: I will put **EnableEndpointStats** in `ir.Metrics`, since adding this feature will require setting the cluster in the `buildXdsCluster` function.

There is currently a problem: `buildXdsCluster` is called by different `processXXXListenerXdsTranslation`, and the parameters of these functions are not consistent. If we plan to support endpoint metrics for all protocols, this will change the parameters of many functions. Big changes to the code.

Currently we are considering whether to enable **EnableEndpointStats** only under HTTP, or whether to enable it under all protocols. I want to hear your opinions. Thanks  :)

@envoyproxy/gateway-maintainers

**Comment by ShyunnY** [comment]
cc @zirain @Xunzhuo

**Comment by ShyunnY** [comment]
@arkodg  WDYT [comment](https://github.com/envoyproxy/gateway/issues/2824#issuecomment-2001878575)

**Comment by arkodg** [comment]
not sure I exactly understand @ShyunnY, here's what Im thinking
* add a new field under ir.Metrics as youve suggested
* add another field in xds cluster args https://github.com/envoyproxy/gateway/blob/a5bedbc71037b9ea7c07b9aa69d3d9218c92d0dc/internal/xds/translator/cluster.go#L40
* build/translate in https://github.com/envoyproxy/gateway/blob/a5bedbc71037b9ea7c07b9aa69d3d9218c92d0dc/internal/xds/translator/cluster.go#L77

**Comment by ShyunnY** [comment]
Yes, you're absolutely right, that's exactly what I was thinking.

But another problem arises at this time:
The upper caller of `buildXdsCluster` is `addXdsCluster`, and `addXdsCluster` is called by different callers. We will find a phenomenon: `*ir.Metrics` seems to only appear in `processHTTPListenerXdsTranslation`:
https://github.com/envoyproxy/gateway/blob/a5bedbc71037b9ea7c07b9aa69d3d9218c92d0dc/internal/xds/translator/translator.go#L118-L124

Based on the information above, going back to the original comment, do we currently only support endpoint stats under HTTP? This question has made me hesitant about how to proceed with writing this PR, because I'm not sure.

**Comment by arkodg** [comment]
we should support for all, the existing field in that IR (virtualHostStats) is related to HTTP, so the initial commit was only applied to HTTP

**Comment by zirain** [comment]
will this cause high cost of memory?
