### ISSUE TITLE
Support LB priority for endpoints

### ISSUE THREAD

**Issue by guydc** [envoyproxy/gateway#3055]
*Description*:
Envoy supports [routing priorities](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/priority#arch-overview-load-balancing-priority-levels):
- When load balancing traffic, envoy uses healthy endpoints (as determined by configured health checks). 
- Users can assign priorities to endpoints, determining which healthy endpoints are preferred for load balancing. 

This allows users to configure a failover mechanism from primary to secondary endpoints.  

Envoy Gateway currently configures a default priority for all endpoints: 
https://github.com/envoyproxy/gateway/blob/f9409e477e866a012757bb9eb4cbc9ac35c7f3a7/internal/xds/translator/cluster.go#L408

LB Priority can be implemented by extending existing Gateway-API resource: 
- `BackendRefs` may support a priority field, similar to the [existing weight](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.BackendRef) field. 
- The `BackendLBPolicy` [resource](https://gateway-api.sigs.k8s.io/geps/gep-1619/?h=backendobjectrefere#backendlbpolicy-api) may be extended to support additional LB considerations, such as priorty. 

Other options:
- EG can support this as an additional attribute of the extended BackendRef proposed in #3069 
- EG can support a custom BackendRef target, which will include a priority field, such as the proposed Backend API: #3063 
- EG `BackendTrafficPolicy` can be used to assign priorities. For example, the policy will hold a map of BackendRefs to priorities. Or, the policy can attach directly to Service resources.

**Comment by arkodg** [comment]
ideally prefer if this was in upstream 
relates to https://github.com/kubernetes-sigs/gateway-api/discussions/2304 & https://github.com/kubernetes-sigs/gateway-api/issues/1802

**Comment by arkodg** [comment]
if we add into field into non xRoute backendRefs, we may need to pluraize existing instantiations to `backendRefs`
* ext auth
* otel 
cc @guydc @zirain

**Comment by guydc** [comment]
> if we add into field into non xRoute backendRefs, we may need to pluralize existing instantiations to `backendRefs`

Yes, also ext-proc. I don't object, and this is in-line with gateway-api. Do you think that we should consider a different intermediate approach?

**Comment by arkodg** [comment]
I'd vote to pluraize the backendRefs for non xRoute asap while we are in alpha, which can be a good place to test the `priority` / standby use case

**Comment by modatwork** [comment]
This could be used to solve https://github.com/envoyproxy/gateway/issues/1909, though it may require further refinement. Specifically, the Envoy Gateway should allocate distinct priority levels to the same upstream endpoint, varying by the Envoy Pod’s location in different availability zones. For instance, for an identical endpoint in zone A, the Envoy Pod situated in zone A should be assigned priority 0, whereas Envoy Pods in zones B and C should be assigned priority 1.

Do you think Envoy Gateway will handle this? Or leave it to the user?

**Comment by guydc** [comment]
> Do you think Envoy Gateway will handle this? Or leave it to the user?

We briefly discussed this scenario in the community meeting. It seems like this will require pushing different config to different envoy proxies based on zone information. For the time being, we'll focus on supporting the simpler use case described above.

**Comment by aoledk** [comment]
As mentioned in https://github.com/envoyproxy/gateway/issues/1909#issuecomment-2126782250, Envoy in different zones may use same backend endpoint as different priority to reduce cross-zone cost.

It's a required feature for production adoption. Does community have roadmap on this feature ?

**Comment by aoledk** [comment]
https://github.com/envoyproxy/gateway/issues/1909#issuecomment-2128073855 says:

> thanks for outlining the steps @aoledk ! we currently have #3055 open to get explicit priority per backendRef and program that into the xds cluster resource.
> 
> In the future, we can use this issue to make sure we track the auto priority work, the field in k8s `preferClose` could be the knob for users to say they want to opt in to this feature

@arkodg One backendRef (mainly Service) will refer to endpoints from multiple zones, priority should not be applied on backendRef, unless we use selector to collect endpoints in same zone into single backendRef.

Besides, same endpoint will have different priority in Envoy.

So maybe we can't assign a fixed priority for backendRef, codes will be needed to assign right priority for specific Envoy.

**Comment by arkodg** [comment]
there are two use cases for priority
* the one you've highlighted where `zones` represent physical locations so location aware routing reduces overall latency as well as cost (cross zone or region can be billed by cloud provider)
* creating a primary and backup backendRef for HA cases (ends up using the same `priority` field in Envoy)

**Comment by aoledk** [comment]
@arkodg Can we add a new xDS Hook API, like `PostEndpointModify(ClusterLoadAssignment, Node)` which allow extension server to assign endpoint priority for individual envoy. Leave these tasks to EG adopters themselves.

**Comment by aoledk** [comment]
> hey @aoledk thanks for driving this work, before we implement this, we as a community need to align on what the feature is, is it
> 
> * Auto Zone Aware Routing where a user sets a global field to enable this, and envoy proxy prioritizes endpoints in the same zone based on its zone ?
>   Open Questions:
>   
>   * is this granular enough ? there are only 2 levels here - `local` or not local
> * Priorites for BackendRefs - Prioritizes one backendRef over another backendRef within the same HTTP Rule

@arkodg I've quoted your https://github.com/envoyproxy/gateway/issues/3538#issuecomment-2153387620 here to continue discussion about priority. I'll freeze #3542 until we reach agreement.

---

Assuming two cases demonstrated in image below.

Case A: priority isn't in gateway-api, EG will generate `#1`, `#2` LocalityLbEndpoints.

Case B: priority is in gateway-api, EG will generate `#3`, `#4`, `#5`, `#6` LocalityLbEndpoints.

![Priority](https://github.com/envoyproxy/gateway/assets/1448783/c44788a8-c8ef-45e2-855b-eb4a88a22cd4)

Code in `xds/cache` will be used to modify priority for individual envoy based on envoy's running topology.

https://github.com/envoyproxy/gateway/blob/33fceb05ca611e30107ff841cac9d7762eea2048/internal/xds/cache/snapshotcache.go#L92-L96

We can have 2 options to enable topology aware routing ( **NOT** [envoy zone aware routing](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/zone_aware) ) based on priority.

### Option 1

Add knob into BackendTrafficPolicy to enable topology aware routing for affected BackendRefs.

If we enable in Case A, `#1`, `#2` LocalityLbEndpoints for envoy running in zone a will be modified by `xds/cache` like this:

- `#1` P=0
- `#2` P=1

If we enable in Case B, `#3`, `#4`, `#5`, `#6` LocalityLbEndpoints for envoy running in zone a will be modified by `xds/cache` like this:

- `#3` P=0
- `#4` P=1
- `#5` P=2
- `#6` P=3

But this option has several challenges.

#### Challenge 1

The new knob is accessible in `xds/translator`, but `xds/translator` only pass `xds` to `xds/server`, then to `xds/cache`, a new communication channel need to be setup to pass this particular knob to `xds/cache`. It will add additional dependency between those modules.

#### Challenge 2

Should we allow user to enable topology aware routing for BackendRefs specified with priority ?

If yes, that means `xds/cache` will modify LocalityLbEndpoints's priority specified by user.

### Option 2

Add knob into EnvoyGateway to enable topology aware routing for all BackendRefs.

If enabled, `#1`, `#2`, `#3`, `#4`, `#5`, `#6` LocalityLbEndpoints for envoy running in zone a will be modified by `xds/cache` like this:

- `#1` P=0
- `#2` P=1
- `#3` P=0
- `#4` P=1
- `#5` P=2
- `#6` P=3

#### Challenge 1

Same to Option 1's Challenge 2.

---

> is this granular enough ? there are only 2 levels here - `local` or not local

LocalityLbEndpoints can be set with `region` / `zone` / `sub_zone`:
- `zone` can be retrieved from EndpointSlice directly.
- `region` can be retrieved like this: use nodeName in EndpointSlice to query Node, retrieve region from Node `topology.kubernetes.io/region` label.
- sub_zone` can't be retrieved.

Envoy can be set with `region` / `zone` / `sub_zone`.
- Since [Pod downward API](https://kubernetes.io/docs/concepts/workloads/pods/downward-api) doesn't expose Pod zone, `region` and `zone` can be retrieved like this: use nodeName via Pod downward API to query Node, retrieve region and zone from Node `topology.kubernetes.io/region` and `topology.kubernetes.io/zone` labels.
- `sub_zone` can't be retrieved.

So `region` can be used as level bigger than `zone` technically, we can discuss whether we need to use `region` on topology aware routing.

**Comment by arkodg** [comment]
thanks for the detailed analysis @aoledk !
1) looks like the "priority is in gateway api backendRef" case is simpler and straightforward and doesnt need zone based endpoint aggregation

Auto Zone Aware Routing
2) if we okay with 2 level priorities then envoy's inherent zone aware routing feature is the way to go
Pros
* easier to build / less complex to maintain and debug
Cons
* only 2 levels of priority - local to envoy or not
3) if we want multi level priority based on `region` / `zone` / `sub zone`, we'll have to key EDS o/p in the control plane  based on envoy locality and start maintaining this extra dimension
Pros
* more levels of priority 
Cons
* need to maintain per locality endpoint cache


As next steps, here is what I propose
1. Decide on which feature we want to prioritize first or both ?
2. For Zone Aware Routing gather more feedback on which how many level priority / locality we want to support

**Comment by alexwo** [comment]
> thanks for the detailed analysis @aoledk !
> 
> 1. looks like the "priority is in gateway api backendRef" case is simpler and straightforward and doesnt need zone based endpoint aggregation
> 
> Auto Zone Aware Routing 2) if we okay with 2 level priorities then envoy's inherent zone aware routing feature is the way to go Pros
> 
> * easier to build / less complex to maintain and debug
>   Cons
> * only 2 levels of priority - local to envoy or not
> 
> 3. if we want multi level priority based on `region` / `zone` / `sub zone`, we'll have to key EDS o/p in the control plane  based on envoy locality and start maintaining this extra dimension
>    Pros
> 
> * more levels of priority
>   Cons
> * need to maintain per locality endpoint cache
> 
> As next steps, here is what I propose
> 
> 1. Decide on which feature we want to prioritize first or both ? This is a great roadmap item for v1.2 (Oct 2024)
> 2. For Zone Aware Routing gather more feedback on how many levels of priority / locality we want to support

If it make sense, we can start with ->1 and extend this struct:
https://github.com/envoyproxy/gateway/blob/a43cc6c96ac147ce58db9714283e77d237c3d1e3/api/v1alpha1/shared_types.go#L471
, with a priority field. Similar to how gwapiv1.BackendObjectReference has "weight". Then, translate this value to an envoy endpoint priority:
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/endpoint/v3/endpoint_components.proto#envoy-v3-api-msg-config-endpoint-v3-localitylbendpoints
 
We can also have an E2E test for this, where we demonstrate that when a high-prio backend is down, traffic is steered to the low prio backend. 
This will only work for "technical" backends at the moment, like ext-auth/proc/observability sinks ...

If sounds good I can assign the ticket on myself and get started ?

**Comment by arkodg** [comment]
hey @alexwo thanks for lookiing into this !
im hoping we can weigh in pros/cons of an explicit `priority` field vs adding another field like `backupBackendRef`

note for @aoledk who is looking into Zone Aware Routing, priority routing is mutually exclusive to it, and EG should be able to do zone aware routing for P=0 Hosts

**Comment by arkodg** [comment]
GCP expresses failover using a `bool failover` field inside backend definition
https://cloud.google.com/compute/docs/reference/rest/v1/backendServices

**Comment by alexwo** [comment]
> GCP expresses failover using a `bool failover` field inside backend definition https://cloud.google.com/compute/docs/reference/rest/v1/backendServices

We could simplify the API by using a boolean and handling the priority at the translation level, with only two priority levels: primary and backup (0,1), like they offer in GCP.

**Comment by arkodg** [comment]
nginx has a `backup` keyword It uses https://nginx.org/en/docs/http/ngx_http_upstream_module.html

I'm a +1 for the boolean option 

also @alexwo another design decision is around when does an endpoint get removed from the load balancing pool and when does it get re added ? is the user responsible for setting up `healthCheck`  (active or passive) which results in endpoints being removed/readded from the pool ?

**Comment by alexwo** [comment]
Sounds good @arkodg  / @guydc   
I have updated my PR to reflect the “designated failover boolean” approach.
