### ISSUE TITLE
Link helm reference docs on helm installation page

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#3366]
*Description*:
>Describe the issue.

The Helm installation page https://gateway.envoyproxy.io/latest/install/install-helm/ should have a link to the helm reference docs
https://github.com/envoyproxy/gateway/blob/main/charts/gateway-helm/README.md

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by shahar-h** [comment]
@arkodg there is already a link to helm chart values:
<img width="620" alt="image" src="https://github.com/envoyproxy/gateway/assets/16555289/9a735fd1-327b-4d50-a1ed-748005192d29">
https://gateway.envoyproxy.io/v1.0.1/install/install-helm/#using-valuesyaml-file-for-complex-installation

However, I noticed that values section in chart [README.md](https://github.com/envoyproxy/gateway/tree/main/charts/gateway-helm#values) is not updated.
The reason is only `site/content/en/latest/install/api.md` is updated when running `make helm-readme-gen`: https://github.com/envoyproxy/gateway/blob/c30d09f284e1ecc0a18a59dbe015987c6a713b1f/tools/make/docs.mk#L38-L42

**Comment by arkodg** [comment]
thanks for finding this @shahar-h, looks like the presentation is not ideal, @yuluo-yx can we move the line right after https://gateway.envoyproxy.io/v1.0.1/install/install-helm/#helm-chart-customizations ?

**Comment by yuluo-yx** [comment]
> thanks for finding this @shahar-h, looks like the presentation is not ideal, @yuluo-yx can we move the line right after https://gateway.envoyproxy.io/v1.0.1/install/install-helm/#helm-chart-customizations ?

got it, I will move.

**Comment by yuluo-yx** [comment]
done. pls review @arkodg
