### ISSUE TITLE
Resolve Service to Endpoints IPs

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#35]
https://github.com/envoyproxy/gateway/pull/16 specifies the need for a Service Resolver (SR) component that resolves IR services into platform-specific endpoints. The SR details should be captured in this issue or a linked doc.

**Comment by danehans** [comment]
The service resolver is currently the responsibility of a provider. I'm moving this issue to the backlog for now.

**Comment by danehans** [comment]
@arkodg can this issue be closed?

**Comment by arkodg** [comment]
we dont need a full fledged service resolver design & implementation, but a reconciler within `provider` is needed to aggregate service endpoints. should be doable for 0.3.0

**Comment by danehans** [comment]
I suggest holding this issue until https://github.com/envoyproxy/gateway/pull/702 is merged.

**Comment by arkodg** [comment]
@zhshw can you help with this issue ?

**Comment by zhshw** [comment]
@arkodg I'm working on it...

**Comment by arkodg** [comment]
thanks @zhshw .
Outlining the pieces needed to implement this issue
* Reconciling the EndpointSlice https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/ in the provider https://github.com/envoyproxy/gateway/blob/5b8b24e1845cc18b5c08bf86b020154c365e968b/internal/provider/kubernetes/controller.go#L186
* Saving it the watchable map https://github.com/envoyproxy/gateway/blob/5b8b24e1845cc18b5c08bf86b020154c365e968b/internal/gatewayapi/resource.go#L24
* Generating the IR RouteDestinations based on the EndpointSlice info in https://github.com/envoyproxy/gateway/blob/5b8b24e1845cc18b5c08bf86b020154c365e968b/internal/gatewayapi/route.go#L678

**Comment by zhshw** [comment]
Thanks @arkodg.

The endpoint is updated frequently. It should be an independent workqueue.
Endpoint-slices reduce data transmission and optimize network throughput, But there may be some problems
endpoint-slices
- Kubernetes v1.21 [stable]
- Kubernetes v1.26 [GA]
 
Kubernetes < 1.26
https://github.com/kubernetes/kubernetes/issues/85643
Terminating Endpoints need to be removed by service (cluster), Otherwise, the flow may be lost
However The pod in the Terminating state is ready

Kubernetes >= v1.21 
Use endpoint-slices stable API, It is necessary to get the status of pod at the same time to determine whether to enter Terminating

Kubernetes General version
Use endpoint API with Pod watch, But network throughput has not been optimized

Improvement Goal
Refer to endpoint-slices GA to design envoy-endpoint, Update envoy-endpoints by watching for pod status update. Minimum data listening amount, maximum Kubernetes version support range

Things don't seem so simple...

**Comment by danehans** [comment]
Since we will need an abstraction to supports multiple implementations, WDYT about starting off with endpoints instead of endpoint slices and iterating? We could introduce endpointslices thereafter.

**Comment by danehans** [comment]
@zhshw I just cleared the stale status for this issue. Are you still planning to work on this?

**Comment by arkodg** [comment]
unassigning @zhshw for now, will reassign again if interested, adding the `help-wanted` tag for this important feature

**Comment by arkodg** [comment]
closing in favor of https://github.com/envoyproxy/gateway/issues/1256
