### ISSUE TITLE
Perform OIDC authentication and authorisation at gateway level

### ISSUE THREAD

**Issue by bbusioc** [envoyproxy/gateway#3525]
Is it possible with envoy gateway to perform OIDC authentication and authorisation at gateway level.
Our use case is that we have some applications that we don't develop and that expose UIs which do not support any type of authentication nor authorisation.
Currently we are adding this with an ingress controller capable to integrate with an IDP provider via OIDC and authorise the requests based on JWT claims and ingress annotations.
We would like to switch in all of our infrastructure from ingress to gateway and we are checking if there is this functionality in envoy gateway.
If this is feasible, is it possible to have some more details/documentation about how it could be achieved?

**Comment by arkodg** [comment]
hey @bbusioc should be possible, can you try out the example tasks outlined in https://gateway.envoyproxy.io/v1.0.1/tasks/security/oidc/ ?

**Comment by benediktwerner** [comment]
1. You just need to make sure the callback URL is a valid route. Envoy will intercept it so it doesn't really matter what backend it references (if any). But if it's not a valid route, you will get a 404 due to no route matching. In our case, we just added a fallback route without a condition (i.e. matching all routes that don't match anything else) that redirects to the home page of our main application. Not entirely sure but possibly it even works without any backend reference or redirect filter (which will also give a 404 according to the gateway spec but I assume counts as a valid route?). But you could also just add a route specifically for the callback path that does some random redirect. Or simply adjust the callback path so that it falls within another sensible valid route.

2. You can specify a JWT extractor in a security policy to extract claims and use that to influence routing. In theory, Envoy also has an RBAC filter which could have more elaborate rules but I don't think Envoy Gateway has support for that yet. Though I guess you could always use it via an envoy patch policy.

**Comment by bbusioc** [comment]
ok, thanks for the feedback. I'll give it a try in the next days; unfortunately it will take a bit longer because in my company we have an internal IDP and the creation of a new partnership takes a while.
but I'll get back here with a comment with the outcome when I'll be able to test it

**Comment by zhaohuabing** [comment]
Closing this as it's already supported.
