### ISSUE TITLE
Add Support for modifying Pod and Container SecurityContext for Envoy Gateway deploment in Helm

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#3887]
*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by Manoramsharma** [comment]
Hi @zhaohuabing after following this discussion for adding support for modifying `SecurityContext` for EG components like `Gateaway` and `certGen`. I came to find that how it can be something to enhance security by initially setting a default(minimize) permissions to the EG components but can be later modified by changing securityContext using this support. 

I saw this [PR](https://github.com/envoyproxy/gateway/pull/3940)  that configures the SecurityContext for EG components to minimize the required permission for operation. 

- CertGen
- Gateway
- ShutdownManager
- Envoy

How can I move forward with this issue as I would like to contribute to add this support for modifying the securityContext?

cc: @arkodg

**Comment by zhaohuabing** [comment]
@Manoramsharma  , thank you for being willing to take this on. Before we proceed with exposing these SecurityContexts to the Helm chart Values file, I’d like to understand a concrete use case. We've already made efforts to minimize permissions to only what the EG components require.

Here’s my suggestion:

If there are any unnecessary permissions in the default settings that EG doesn’t need, we should consider removing them.
If a user has a requirement where the default settings don't fulfill their use case—such as needing additional permissions due to a customized Envoy deployment—we can then discuss how best to expose these SecurityContexts to the Helm chart Values file.
Does this approach make sense? Do you have a specific use case where you need to customize these SecurityContexts?

**Comment by akorosi** [comment]
Hi,
We are adding Opentelemetry Collector Sidecar to gateway pods using specific annotations, but we see pods are failing, because 
`kubelet            Error: container has runAsNonRoot and image will run as root (pod: "envoy-gateway-77f56f76d-4lf2x_gateway(9ceff3d6-7a4a-4378-83e3-eb33e0452541)", container: otc-container)`

If I manually edit the Deployment and change securityContext to false, then pod can start properly. It would be good that this attribute could be customizable

**Comment by zirain** [comment]
will https://gateway.envoyproxy.io/docs/api/extension_types/#kubernetespatchspec help?

**Comment by arkodg** [comment]
for envoy proxy you can set the pod security context using `EnvoyProxy` API https://gateway.envoyproxy.io/docs/api/extension_types/#kubernetespodspec

completion of this issue should allow modifying the pod Security context of Envoy Gateway deployment

**Comment by zhaohuabing** [comment]
@akorosi The `runAsRoot` has been removed from the Pod SecurityContext and moved into the Envoy Gateway container SecurityContext in PR [set default SecurityContext for EG components](https://github.com/envoyproxy/gateway/pull/3940) and will be available in the next release v1.2.0. It won't block the Opentelemetry sidecar container from running as Root anymore.
