### ISSUE TITLE
Support multiple backendRefs

### ISSUE THREAD

**Issue by guydc** [envoyproxy/gateway#4006]
*Description*:
We currently limit the size of []BackendRef in policies (Security, Extension) and EnvoyProxy to 1, due to CEL validation complexity.  
Naturally, a list is used in the API because we do intend to support more than one BackendRef.

**Comment by liorokman** [comment]
I think this isn't the case anymore after #3069.

**Comment by arkodg** [comment]
can this be closed @guydc  ?

**Comment by guydc** [comment]
Had a discussion with @liorokman about this. BackendCluster currently supports >1 backendRefs, but the actual usages limit the list size to 1, e.g. here:
https://github.com/envoyproxy/gateway/blob/7c1d50991deacf6619ca776912cd445e35266f61/api/v1alpha1/ext_proc_types.go#L50

@liorokman looked into this, and to truly support this multiple backendRefs for non-xRoutes (with cluster settings), we maybe need to implement some additional translation steps and handle possible conflicts (e.g. mismatched endpoint types, application protocols, etc.). 

Let's keep it open for the time being.

**Comment by liorokman** [comment]
The CEL validations currently limit the `backendRefs` array to one element only for Ext-Auth and Ext-Proc.

The Ext-Proc code actually doesn't assume an array of one element, so the fix for Ext-Proc is to simply remove the CEL validation.
Ext-Auth is more complicated and needs some more work.

Tracing, logging, and other `BackendCluster` users already support multiple backendRefs (up to 16, due to CEL validation complexity calculations).
