### ISSUE TITLE
Consider Merging Controllers

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#413]
Since not all Gateway API resources have a parent-child relationship, consider merging controllers into a single reconciler.

xref: https://github.com/envoyproxy/gateway/pull/412
xref: https://github.com/envoyproxy/gateway/pull/403

**Comment by arkodg** [comment]
I prefer if we implement this sooner than later and here's why
* performance
  * adding multiple watches for multiple resource controller means we'll be multiple notifications if a single resource changes, which will trigger multiple redundant translations (due to updating the watchable map)
* code complexity
  * handling deletes - since each resource type is part of a separate watchable map, the logic to perform deletes is non trivial at the moment
  * knowing which resource to to reconcile when another resource is updated is non trivial and error prone

**Comment by chauhanshubham** [comment]
+1
I think we could consider Gateway object as a root object, add a Gateway controller which watches over httproute, tlsroute, services, refgrants. and push these objects into the resource table as the updates come in.

**Comment by danehans** [comment]
> I think we could consider Gateway object as a root object
A GatewayClass must be the root object. All others are objects are dependents of a GatewayClass.

**Comment by skriss** [comment]
+1 to this, I think it will also help down on a lot of code duplication that we're starting to get between the reconcilers and the Gateway API translator, around things like mapping routes to gateways, validating parent refs, etc.

**Comment by chauhanshubham** [comment]
I can take this up, have some psuedo code ready.

**Comment by Xunzhuo** [comment]
Thanks @chauhanshubham
