### ISSUE TITLE
Make certgen optional in helm chart

### ISSUE THREAD

**Issue by lsjostro** [envoyproxy/gateway#4530]
*Description*:
Would be nice to make certgen optional in helm chart. (have job resource wrapped with a conditional like `certgen.enabled: true/false` maybe?)

little silly having to patch away within kustomize like so:
![image](https://github.com/user-attachments/assets/9da1b6dc-4944-4011-879a-a8e3887941d3)

**Comment by arkodg** [comment]
hey @lsjostro we had discussed this earlier in https://github.com/envoyproxy/gateway/issues/3501 and decided to not support a disable knob because the job also creates some secrets needed for OIDC.
If the secrets (for certs or hmac) already exist (if you are setting your own control auth certs), then the cert gen job will skip creating any new secrets (a no-op)
