### ISSUE TITLE
Collapse Gateway API CRDs and Envoy Gateway Installation Manifests

### ISSUE THREAD

**Issue by danehans** [envoyproxy/gateway#485]
Currently, separate manifests are created per release, For example:
```
https://github.com/envoyproxy/gateway/releases/download/v0.2.0-rc2/gatewayapi-crds.yaml
https://github.com/envoyproxy/gateway/releases/download/v0.2.0-rc2/install.yaml
```

This creates an additional installation step that can be eliminated if the manifests were collapsed.

**Comment by AliceProxy** [comment]
This seems like a good idea for now, but something to consider for the future, if we want to make a helm chart available at any point then the CRDs will need to be separated out from the chart again (or have their own chart) since Helm 3 will install CRDs if they are not present, but it will not update the CRDs if they exist in the cluster regardless of any differences. https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations

Since we aren't publishing a  helm chart at the moment though this sounds like a fine idea.
