### ISSUE TITLE
Add support for UDPRoute API

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#641]
*Description*:
Add Support for the UDP Route API defined [here](https://github.com/kubernetes-sigs/gateway-api/blob/21bba43681b3db3a62d7ca9f108bf3be4c0cea71/apis/v1alpha2/udproute_types.go#L33)

Related https://github.com/envoyproxy/gateway/issues/47

**Comment by arkodg** [comment]
we should wait on https://github.com/envoyproxy/gateway/issues/413 which is refactor the provider before kickstarting this

**Comment by zhaohuabing** [comment]
@arkodg May I take this one? It would be a relatively easy start for me to dig into the core mechanism of EG since I can refer to the implementation of the current HTTRoute. If this goes well, I would like to take https://github.com/envoyproxy/gateway/issues/642 as well.

**Comment by arkodg** [comment]
go for it @zhaohuabing . suggesting raising incremental PRs in the below order to increase PR review speeds and reduce merge conflicts :)
* [Xds IR](https://github.com/envoyproxy/gateway/blob/d572c238cfde8623046de85c06b3139479f1d7aa/internal/ir/xds.go#L41)
* [Xds Translator](https://github.com/envoyproxy/gateway/blob/d572c238cfde8623046de85c06b3139479f1d7aa/internal/xds/translator/translator.go#L107)
* [Gateway API Translator](https://github.com/envoyproxy/gateway/blob/d572c238cfde8623046de85c06b3139479f1d7aa/internal/gatewayapi/translator.go#L51)
* Provider (which is currently being refactored)

**Comment by youngnick** [comment]
I'd like to see some work done on how the UDP flows will actually work. It's pretty straightforward to set up a UDP listener for Envoy, but it's very difficult to preserve the client address at the same time.

Basically, you have two options:
- Use Envoy in non-transparent proxy mode, which means that the client address will be seen at the backend pods as Envoy's address. As I said, most UDP protocols don't like this.
- Use Envoy in transparent proxy mode, which means that packets will be forwarded to the backend pods without changing the client IP, *but* the server IP will also not be updated to Envoy's, which means that the return path *from* the backend back to the client will both not go via Envoy, and will be from a different IP address than what the packet was sent to (since it will be the backend's address). Most firewalls will drop UDP traffic like this, that both doesn't come from and address traffic is already heading to, and (most likely) comes from an RFC1918 address.

In particular, on Contour, we've been asked to have Contour handle SIP traffic, and SIP in particular is a very bad fit for this sort of proxying, as the RTP used for the actual data streams (as opposed to the control traffic) is _very_ dynamic and difficult to proxy correctly.

I'm not _opposed_ to doing UDPRoute in Envoy Gateway, but I would like to see significantly more design around how to make it available in a way that meets user expectations. Just adding support for the existing UDP modes in Envoy does not match up to what users will expect when you add UDP forwarding.

**Comment by zhaohuabing** [comment]
I think transparent proxy mode can be benifical for both TCP and UDP since in some use cases, the server behind the EG would like to know the original addreess of the client. To get this done, we'll need to set the route inside a cluster to get the traffic route back to EG, and then EG can send the traffic right back to the client.

**Comment by arkodg** [comment]
@youngnick the  https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/udp_filters/udp_proxy docs states that envoy operates as a non transparent proxy.
The xds implementation does not seem too complex, if you prefer, either @zhaohuabing or I could
PoC with Envoy proxying UDP traffic to a pod running a TFTP server or UDP Ping server and share those details on this issue.
If some UDP protocols dont like `non transparent` mode , we will have have add those limitations to the EG docs for now.

**Comment by zhaohuabing** [comment]
non-transparent proxy should work, I'll test that after the translators implemention is done. transparent proxy mode is also helpful, maybe we could discuss how to support it if there're more requests from the clients to ask for it. Besides, we should also consider the transparent mode for TCP listeners together.

**Comment by arkodg** [comment]
Reread the envoy docs which states that envoy also support transparent mode but needs added privileges ( not given to the envoy deployment today ) 
@youngnick do you have any info handy on which protocols support non transparent mode and which dont ?

**Comment by youngnick** [comment]
It's tricky, but in general UDP protocols expect the client address to be the actual one. DNS, and syslog are the ones I can think of from the top of my head. I'm not sure about other ones - I know that lots of gaming applications use UDP as well. It's going to be on a per-protocol basis though - and lots of people roll their own protocol.

If we really want to do it, it will be extremely important to call out the no-client-address limitations of proxied mode, definitely.

For transparent proxying, changing the routing seems like it needs pretty deep integration with the CNI or kube-proxy - I don't feel like us building that into Envoy Gateway is a very good idea without doing a pretty detailed design first.

**Comment by danehans** [comment]
xref https://github.com/envoyproxy/gateway/pull/646 for adding UDPRoute to IR.

**Comment by danehans** [comment]
> Use Envoy in non-transparent proxy mode, which means that the client address will be seen at the backend pods as Envoy's address. As I said, most UDP protocols don't like this.

Although most UDP protocols don't like this, non-transparent proxy mode could be considered "initial" UDPRoute support. We can document these details while we work on a long-term UDPRoute solution that covers the other UDP protocols.

@mattklein123 PTAL at this issue and #643. Let us know if you have any input on adding L4 support.

**Comment by danehans** [comment]
> For transparent proxying, changing the routing seems like it needs pretty deep integration with the CNI or kube-proxy 

Maybe a solution similar to kube-proxy's [internalTrafficPolicy: Local](https://kubernetes.io/docs/concepts/services-networking/service/#external-traffic-policy) can help workaround this issue?

**Comment by arkodg** [comment]
cc @moderation

**Comment by youngnick** [comment]
> > For transparent proxying, changing the routing seems like it needs pretty deep integration with the CNI or kube-proxy
> 
> Maybe a solution similar to kube-proxy's [internalTrafficPolicy: Local](https://kubernetes.io/docs/concepts/services-networking/service/#external-traffic-policy) can help workaround this issue?

Sadly, it's not about the _inbound_ traffic, transparent mode will get the packets _to_ the backend properly. It's about the return path _from_ the backend back to the client - because Envoy doesn't do any address translation, the packets will be sent straight from the backend to the client, _without going back through Envoy_. To change that behavior, you'd need to mess with the routing tables for the pod, basically making Envoy the default gateway for all IP traffic in the pod (this is how traditional load balancers like F5 work, they're almost always the default gateway for the segment where the backends reside).

**Comment by moderation** [comment]
@youngnick a couple of questions:

1. NGINX in theory supports UDP ingress today irrespective of Envoy Gateway - do they have a feature or implementation that differs from Envoy that enables them to provide this UDP ingress solution
2. Ambassador Labs Emissary Ingress which is based on Envoy supports HTTP/3. HTTP/3 rides on QUIC which is UDP based. What are they doing that is out of reach for Envoy Gateway supporting UDP?

**Comment by youngnick** [comment]
> @youngnick a couple of questions:
> 
> 1. NGINX in theory supports UDP ingress today irrespective of Envoy Gateway - do they have a feature or implementation that differs from Envoy that enables them to provide this UDP ingress solution

No, from what I can see, their UDP implementation will have the same client address limitation. I seem to recall looking at a version of their documentation that called this out, but I can't see it in their current one. 

In addition, the fact that their Service Mesh product uses eBPF to inject PROXY protocol headers in order to make this work tends to bear this out, for me.

> 2. Ambassador Labs Emissary Ingress which is based on Envoy supports HTTP/3. HTTP/3 rides on QUIC which is UDP based. What are they doing that is out of reach for Envoy Gateway supporting UDP?

QUIC is different, because QUIC uses UDP as a _transport_, but has higher-layer constructs to allow the backend to rebuild the actual client address (like X-Forwarded-For in HTTP/1 and HTTP/2). So it doesn't matter in those cases if the actual client IP is lost along the way.

Most other UDP protocols don't have this, sadly.

> 3. Should the documentation of the Kubernetes Gateway API specification modify their documentation to indicate that of the reverse proxies, Envoy is unable to support `UDPRoute`?

It's not really a matter for Gateway API - Gateway API defines what a UDPRoute *is* - the fact that Envoy running as an in-cluster proxy can't do it isn't really relevant there.

I would love to have a way to make this work the way we all want it to, but trying to proxy UDP with cluster networking really is the worst-case scenario, sadly.

**Comment by zhaohuabing** [comment]
It seems like we don't have a workable solution for trasparent proxying for UDP and TCP. So I'll go with the non-trasparent mode and add some documentation on that to make it clear to the users. Does this sounds good?

**Comment by arkodg** [comment]
lets keep this issue open until end to end functionality is shown in the docs

**Comment by danehans** [comment]
@zhaohuabing do you mind adding a user doc to close out this issue?

**Comment by zhaohuabing** [comment]
@danehans Sorry for the delay. My hands were tide for the last few weeks. I'll add the doc this week and close this issue.
