### ISSUE TITLE
update to Kubernetes 1.26.x

### ISSUE THREAD

**Issue by skriss** [envoyproxy/gateway#682]
*Description*:
EG should be compatible with and tested against the latest Kubernetes 1.25.x.

Tasks:
- [x] upgrade metallb to latest (current version uses PSP which is no longer available in Kube 1.25)
- [x]  upgrade kind to latest
- [x]  update conformance test matrix node images (pending https://github.com/envoyproxy/gateway/pull/681) 
- [ ]  update k8s go modules

**Comment by danehans** [comment]
Reopened since the k8s.io deps should still get bumped to v1.25.

**Comment by skriss** [comment]
ref. https://github.com/kubernetes-sigs/gateway-api/pull/1587

**Comment by skriss** [comment]
I'd suggest updating this to be for Kube 1.26 (including modules, kind cluster for conformance tests, etc) since it's out now. Supported Kubernetes versions would be 1.24 - 1.26.

**Comment by danehans** [comment]
@skriss thanks for the heads-up that k8s 1.26 is now available. I'm unassigning myself since I don't have the available bandwidth to fix this issue for v0.3. Hopefully, someone else can take on this issue. @jcheld are you able to help with this? It can be a good first issue and you can reference https://github.com/envoyproxy/gateway/pull/767 for guidance.

**Comment by danehans** [comment]
Thanks at @jcheld! I just assigned you the issue. Let us know if you have any questions.
