### ISSUE TITLE
Support configuring number of replicas of Envoy Proxy

### ISSUE THREAD

**Issue by gitanuj** [envoyproxy/gateway#713]
Currently EG deploys only a single instance of Envoy Proxy. For scaling to high number of requests it will be useful to be able to increase number of replicas of Envoy Proxy to distribute load. It can be used for the following scenario -
- Deploy EG with one replica of Envoy Proxy
- As the traffic increases, metrics report high CPU usage of Envoy Proxy pod
- Increase the number of replicas of Envoy Proxy to distribute the load and reduce CPU usage per pod

This property can be exposed through [Envoy Proxy Config API](https://github.com/envoyproxy/gateway/blob/v0.2.0/api/config/v1alpha1/envoyproxy_types.go) - #703

**Comment by danehans** [comment]
@gitanuj tya is for creating the issue. Are you willing to work on a PR to fix this issue? If so, I would be happy to help provide guidance.

**Comment by gitanuj** [comment]
@danehans It'll be great if you can give me some pointers to get started on this and I can work on it sometime next week. Would love for this to be included in the next release.

**Comment by danehans** [comment]
Since the EnvoyProxy API is currently unimplemented, fixing this issue will require more work than what will be needed in the future.

### Implementation Tasks

- [ ] Review the [config API dev guide](https://gateway.envoyproxy.io/v0.2.0/design/config-api.html#data-plane-api) for background on the Envoy Gateway data plane API, e.g. EnvoyProxy.
- [ ] Update the EnvoyProxySpec API to define the schema for managing the Envoy deployment, e.g. the number of replicas. Avoid any Kube-isms as we intend for Envoy Gateway to support managing Envoy in non-Kube environments. Use kubebuilder validation [markers](https://book.kubebuilder.io/reference/markers/crd-validation.html) as needed. After your changes are complete, generate the DeepCopy methods `make generate`.
- [ ] Update [ProviderResources](https://github.com/envoyproxy/gateway/blob/main/internal/message/types.go) to include EnvoyProxy. The field should follow the pattern of existing namespaced name fields, e.g. `EnvoyProxies watchable.Map[types.NamespacedName, *v1a1.EnvoyProxy]`. Update the Envoy Gateway [server command](https://github.com/envoyproxy/gateway/blob/main/internal/cmd/server.go) to close the EnvoyProxies channel upon shutdown.
- [ ] [Infra IR](https://github.com/envoyproxy/gateway/blob/main/internal/ir/infra.go)- Update the `ProxyInfra` methods to include EnvoyProxy. Note that the infra IR already supports EnvoyProxy.
- [ ] Update the [resource translator](https://github.com/envoyproxy/gateway/blob/main/internal/gatewayapi/translator.go)- EnvoyProxy should be added to the `Resources` type. The `Translate()` method should be updated to include the EnvoyProxy in the infra IR (if one exists). Update the [runner](https://github.com/envoyproxy/gateway/blob/main/internal/gatewayapi/runner/runner.go) to subscribe to the EnvoyProxies channel.
- [ ] Update the [gatewayclass controller](https://github.com/envoyproxy/gateway/blob/main/internal/provider/kubernetes/gatewayclass.go) of the Kube provider to check if the accepted GatewayClass [references](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.ParametersReference) an EnvoyProxy. If the reference is invalid, have the `statusUpdater` update the GatewayClass status with the [InvalidParamters](https://github.com/kubernetes-sigs/gateway-api/blob/v0.5.1/apis/v1beta1/gatewayclass_types.go#L165-L168) condition. If the reference is valid, get and store the EnvoyProxy in the resource map. Delete the EnvoyProxy from the resource map when the GatewayClass is deleted. Create a watch for EnvoyProxy and update the GatewayClass status and the resource map accordingly. You can reference the [gateway controller](https://github.com/envoyproxy/gateway/blob/main/internal/provider/kubernetes/gateway.go) for watches examples. Note that https://github.com/envoyproxy/gateway/pull/702 is consolidating the controllers into a single reconciler.
- [ ] Implement the EnvoyProxy API changes in the [Kube infra manager](https://github.com/envoyproxy/gateway/tree/main/internal/infrastructure/kubernetes).

__Notes__:

- Tasks should be implemented as separate PRs.
- Includes tests for added functionality.
- Make sure all tests pass before pushing a PR. See the [dev guide](https://gateway.envoyproxy.io/v0.2.0/dev/README.html) for details.

@arkodg @skriss @AliceProxy @Xunzhuo feel free to provide any additional guidance.

**Comment by danehans** [comment]
@arkodg thanks for sharing the Istio reference. If we take the [KubernetesResourcesSpec](https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/#KubernetesResourcesSpec) approach, EnvoyProxy will need a higher-level abstraction similar to [provider](https://github.com/envoyproxy/gateway/blob/v0.2.0/api/config/v1alpha1/envoygateway_types.go#L37-L42) in EnvoyGateway to wrap the Kube-isms. For example:

```yaml
apiVersion: config.gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoyproxy-sample
spec:
  provider:
    type: Kubernetes
    kubernetes:
      replicasCount: 2
...
```

The KubernetesResourcesSpec approach provides a high level of configurability. However, it also provides a higher support burden and potential UX issues over a more fine-grained API surface.

**Comment by arkodg** [comment]
yah @danehans above approach looks good
reg level of customizations, imho EG should provide the subset of deployment & service kubernetes customizations to allow the user to run EG in production, and it will have to be via such a config API because Envoy proxy is being deployed programmatically
