### ISSUE TITLE
Support k8s Service ExternalName

### ISSUE THREAD

**Issue by zhshw** [envoyproxy/gateway#873]
*Description*:

For cross namespace access, an ExternalName type service is usually configured.

the eg does not support or validate this service type.

For envoy, it is just a DNS discovery. It can support....

Other：
- ingress-nginx support ExternalName service

**Comment by danehans** [comment]
EG supports creating a Gateway in a different namespace than an HTTPRoute. An HTTPRoute can route to a Service in a different namespace by using a ReferenceGrant. Does this not meet your use case? If not, please help us better understand.

**Comment by zhshw** [comment]
See ReferenceGrant in the latest code. I will test whether it supports the ExternalName type service

**Comment by qicz** [comment]
In other cases, call the specified domain name directly. so support k8s service externalName is a great job

**Comment by youngnick** [comment]
As @danehans  said, this is not needed for Gateway API resources, because you can use ReferenceGrant with services that are stored in other namespaces. In fact, ReferenceGrant was designed precisely to make ExternalName services _not_ required, for the following reason:

Supporting ExternalName is a massive security hole; see this issue we previously had on Contour. https://github.com/projectcontour/contour/security/advisories/GHSA-5ph6-qq5x-7jwc . It can also be used for bypassing any cross-namespace restricctions - you can use a `servicename.svc.namespace.cluster.local` domain name to reference any service you know of in the cluster, rendering ReferenceGrant irrelevant.

We discussed this in our community meeting today, and the maintainers are in agreement that we will not be implementing support for externalName services because of these issues. I'm closing this for posterity, but if you have more to say, please feel free to discuss.

**Comment by arkodg** [comment]
cc @AliceProxy

**Comment by EltonzHu** [comment]
Hi @danehans @youngnick @arkodg , I am revisiting this ticket regarding an Edge CDN use case. I am not sure if community is aware of this use case or not. 

Use case details: Once Envoy proxy on the edge cluster receives specific user request, it will forward the request to ANOTHER cluster through DNS resolution.  I am thinking this can be done through Envoy gateway utilizing externalName service to configure Envoy proxy through cDS with logical DNS / stric DNS approach.

I do understand using externalName has security issues.

I am proposing adding externName feature support by adding enable_externalName option through Envoy gateway control configuration. Default value can be set to false and we can put warnings regarding enabling it.

Any suggestions or work arounds?
Thank you!

**Comment by kfox1111** [comment]
I guess I'm missing it. What flag name needs to  be set with the merged functionality?

**Comment by arkodg** [comment]
* there are still users who are relying on this feature 
* and the FQDN based endpointSlice requires creating 2 resources (Service and EndpointSlice)

Im thinking we could support this as an opt in knob at startup (and disallow `localhost` and highlight the shameless cross namespace boundary crossing in the doc string) cc @envoyproxy/gateway-maintainers @envoyproxy/gateway-reviewers

**Comment by dprotaso** [comment]
FWIW - Knative uses K8s Services type=ExternalName

We were hoping to migrate our use the Service+EndpointSlices but the FQDN feature is considered deprecated - I've been poking on the issue to see if that can be reversed https://github.com/kubernetes/kubernetes/issues/114210

**Comment by winston0410** [comment]
> FWIW - Knative uses K8s Services type=ExternalName
> 
> We were hoping to migrate our use the Service+EndpointSlices but the FQDN feature is considered deprecated - I've been poking on the issue to see if that can be reversed [kubernetes/kubernetes#114210](https://github.com/kubernetes/kubernetes/issues/114210)

I am trying to run Knative with Envoy gateway in front, running into issue and found this. @dprotaso Do you know if there is any workaround right now?

**Comment by arkodg** [comment]
@winston0410 the recommended solution by Envoy Gateway is to
* To use the Backend resource (available in v1.1.0) https://gateway.envoyproxy.io/latest/tasks/traffic/backend/
* Use custom user defined EndpointSlices https://gateway.envoyproxy.io/latest/tasks/traffic/routing-outside-kubernetes/
