### ISSUE TITLE
Install tooling for dev workflows

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#90]
Raising this issue to help reach an engineering decision on what is the best way for this project to install/leverage tooling
for supporting various developer workflows such as generating license for files, using linters and more...

Sharing three ways this is done in most projects today - 
1) Use a build container which comes pre-installed with all tooling needed for developer workflows. 
[Istio](https://github.com/istio/tools/blob/master/docker/build-tools/Dockerfile) and [Envoy](https://github.com/envoyproxy/envoy-build-tools/tree/main/build_container) use this method today

**Pros**
* Easy to add/rm tools for the project
* No binary artifacts

**Cons**
* Some devs prefer running tools natively rather than in a container since they are slower
* Docker builder docker image artifact

2) Use an indirection of replacing the tool name with a local script that lives in `hack/` . The script can do
clever things like either call the tool binary directly, or call the docker image of the tool directly.
This approach is used in [Contour ](https://github.com/projectcontour/contour/blob/main/hack/golangci-lint)today

**Pros**
* Script allows for flexibility

**Cons**
* Hard for the dev (user) and well as code owners to keep track of exact logic 

3) Install the tool binary into the local `bin/` directly using a `make` target and use it
This approach is used by[ Kubebuilder](https://github.com/kubernetes-sigs/kubebuilder) based projects
**Pros**
* The projects installs all the tooling with the right version into the local `bin` directory
making the project
* The tooling installation and the dev workflow logic (make targets) live close to each other
**Cons**
* Binary artifacts

**Comment by arkodg** [comment]
having used all these different patterns in various projects over the last few years, prefer going with 3 which uses minimal tools to get the job done, is a clean coding pattern (that can live in its own Makefile if needed) and is fast.
used it to implement adding license headers to files [here](https://github.com/envoyproxy/gateway/pull/84)

**Comment by lianghao208** [comment]
In option 3, are there always efficient ways to install binary artifacts? 

For example, yaml linter doesn't seem to provide a binary installation doc. On the contrary, a [build container](https://github.com/giantswarm/yamllint-docker/blob/master/Dockerfile) which doesn't require particular user environment(e.g pip, yum) is easier to run. 

xref: https://yamllint.readthedocs.io/en/stable/quickstart.html#installing-yamllint

**Comment by arkodg** [comment]
@lianghao208 good catch, so looks like we could either find a way to download `yamllint` using popular 
package managers - `pip`, `brew`, `apt` or just move the `hack/` logic into the Makefile (checks if binary is present, if not runs a docker image)

**Comment by danehans** [comment]
I lean towards 2 due to my familiarity with the workflow. I don't find the make -> ./hack/foo.sh indirection that difficult to follow and it's a very common approach. 1 would be my 2nd option since it's used by Envoy and provides consistency between the two projects, but running in a container does slow dev down.

**Comment by lizan** [comment]
re 1: Docker builder docker image artifact is a non-issue when using `buildx` or `ko`

I'm leaning toward 1, but we can also do hybrid with 3. Those keeps dev workflows close to CI as well. If you setup devcontainer correctly with 1 it doesn't slow dev down.

**Comment by lianghao208** [comment]
> I don't find the make -> ./hack/foo.sh indirection that difficult to follow and it's a very common approach.

+1, I lean towards 2 as well. Compare to 1, 2 is more flexible and easier for extension as mention.

> move the hack/ logic into the Makefile 

@arkodg IMO, considering it's difficult to reuse `docker run` logic in Makefile(different tool container images may require different `docker run option`, e.g. different `--volume, --workdir`), moving the installation logic into Makefile could increase the complexity and reduce the readability of Makefile.

**Comment by youngnick** [comment]
I think my preference is 2, 1, 3.

I put 2 first because I think that encapsulating logic for operational things into scripts is less cognitive load because you don't need to care about what they do exactly until you need to change it. The scripts also allow you to version-check the tools to ensure a consistent experience (although we haven't done a good job on this with Contour).

At the end of the day, most people are going to be using `make something` to do their local loop anyway. I'd prefer to keep the local targets as similar as possible to the CI ones, so we encourage people to do as much testing as possible locally, and not use CI until you need to.

**Comment by arkodg** [comment]
looks like 1 & 2 seem to be the most popular choices. 2 seems to clearly be the most flexible option, but it could be more time consuming for some edge cases (where the user needs to run a docker container for every tool)
lets start with 2 and we could eventually provide 1 to the user using a `RUN_MAKE_IN_CONTAINER` env

**Comment by arkodg** [comment]
Based on the learnings from https://github.com/envoyproxy/gateway/pull/79
* Some tooling are maintained as a binary and not as a docker image
* The project should make it easier for the dev to run all make targets locally without having to manually install the prerequisite tools

Im in favor of 1
cc @envoyproxy/gateway-maintainers

**Comment by youngnick** [comment]
Yeah 1 sounds fine to me.

**Comment by danehans** [comment]
xref: https://github.com/envoyproxy/gateway/pull/122 for reopening this issue. I find supporting native (mac/linux) + Docker dev envs to be painful.

**Comment by youngnick** [comment]
We discussed in the community meeting that we're going to change this decision to using locally installed tooling only.

Maintainers, please cast binding votes here with a comment or react on this comment. Non-binding votes are also welcomed.

**Comment by danehans** [comment]
+1 to using locally installed tooling only.

**Comment by daixiang0** [comment]
The dev/CI container provides a complete environment for development, which is easy for developers.

If we remove this, developers need to install those tools by hand, which is not easy for dev isolation(some tools may be used in other projects but different versions).

I agree that running in containers may be slow, maybe we can add `.tool` and provide tool installation target for it, that would be better.

**Comment by youngnick** [comment]
As it stands, we have a majority of binding votes in favor of proceeding with locally installed tooling only. I appreciate that this is a contentious decision, but I think our time is better spent on actually getting a functional Envoy Gateway first, and worrying about optimizing the development experience later.

Like any decision, this one is not final, and we can revisit it later, but I think that a revisit of this should be held until after the v0.2.0 milestone, so that we have a chance to try this out for a while.

I'm going to close this issue now to reflect the closed state of the vote. Please feel free to continue to comment with any thoughts or concerns.
