### ISSUE TITLE
 Suggestions on gatewayapi

### ISSUE THREAD

**Issue by zhshw** [envoyproxy/gateway#919]
At present, the design of gatewayapi still lacks sufficient production validation, so it is not necessary to wait for the design of gatewayapi. Just consider enough compatibility with it, Partially use it.  

Keep observing the features in the gateway api design.

The go-controller-plane is also the definition of resources,  Not all resource conversions are translations. It can also be an association.

For example, the association between K8S Service resource and Envoy Cluster resource, Get endpoints and container ports through K8s Service, The actual work is Envoy Cluster.  If there is an EnvoyCluster CRD, the logic will be very simple.

cluster 
<pre>
apiVersion: config.gateway.envoyproxy.io/v1alpha1
kind: EnvoyCluster
metadata:
  name: demo
spec:  //use envoy cluster struct
</pre>

Endpoints
<pre>
apiVersion: config.gateway.envoyproxy.io/v1alpha1
kind: EnvoyEndpoints
metadata:
  name: demo
spec:  //use envoy endpoint struct
</pre>

**Comment by youngnick** [comment]
Thanks for the issue @zhshw.

We actually discussed this approach early on in the design phase for Envoy Gateway, and decided not to go with it because it adds a bunch of additional complexity around handling extra clusters, endpoints etc. At the time, the maintainers didn't believe the benefits (making some translations easier to do) were worth the costs (we still need to translate the Kubernetes Service and Endpoints into these resources anyway, so we're really _moving_ the complexity rather than _reducing_ it).

I'm curious if you have any other reasons aside from those for proposing this? I don't think that the cost/benefit has changed very much, but I'd love to hear if you have some other ideas here.

**Comment by zhshw** [comment]
Translation will result in a large number of intermediate fields and intermediate resource definitions

However, these fields are difficult to match with enough unit tests, design documents, and design validation, which require a lot of time.

Using the envoy controller plane resource field will reduce the user's use cost, and you can refer to the envoy document, without the risk of design failure.

Using this method in basic resources such as cluster and endpoint will only add hundreds of lines of code. But for envoy-gateway, it has a lot of resources and rich configurations that can be user-oriented. 

Different scenarios and requirements, Support for new features will be very fast, not a lot of "Support *" issues

**Comment by arkodg** [comment]
@zhshw your comments reveal that you're well versed in Envoy APIs and can be classified as a advanced user for this project. For users like you we planning on supporting a direct xDS mode, more details here https://github.com/envoyproxy/gateway/issues/24, we will try and prioritize this feature for the next release so users like you can leverage advanced Envoy knobs w/o waiting for it to be exposed in the Gateway API
