### ISSUE TITLE
Enable HTTPRouteRedirectHostAndStatus conformance test

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/gateway#992]
*Description*:
Seeing this fail in https://github.com/envoyproxy/gateway/pull/780

Once fixed they should be enabled via https://github.com/envoyproxy/gateway/blob/main/test/conformance/conformance_test.go

**Comment by arkodg** [comment]
cc @AliceProxy

**Comment by arkodg** [comment]
blocked on https://github.com/kubernetes-sigs/gateway-api/issues/1721

**Comment by AliceProxy** [comment]
There is an upstream issue with Gateway API language on the expected behaviour for redirects when a port is not specified. Currently, Envoy Gateway and Envoy do not do anything if the port is not supplied; however, Gateway API expects port 80 to be appended. After the language changes in Gateway API, the conformance test will need to be updated.
